application:
  name: bikesy-wrapper
osrm:
  profiles:
    standard:
      host: https://bike-mapper-extra-safe-52gon.ondigitalocean.app/route/v1/driving/
    extra_safe:
      host: https://bike-mapper-sq63s.ondigitalocean.app/route/v1/driving/
