application:
  name: bikesy-wrapper
  port: 8888
osrm:
  profiles:
    standard:
      host: https://bikesy-api.herokuapp.com/route/v1/driving/
redis:
  # note that this will rotate.  Config will override with environment variable on deploy.
  url: redis://h:p8e4b4b25361021b8f96a94292d7be59b079c702bdc2ffd9d56582c7df5fbbd03@ec2-54-167-200-131.compute-1.amazonaws.com:13269
