// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ElevationService is an autogenerated mock type for the ElevationService type
type ElevationService struct {
	mock.Mock
}

// GetElevations provides a mock function with given fields: nodes
func (_m *ElevationService) GetElevations(nodes []int) ([]float64, error) {
	ret := _m.Called(nodes)

	var r0 []float64
	if rf, ok := ret.Get(0).(func([]int) []float64); ok {
		r0 = rf(nodes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int) error); ok {
		r1 = rf(nodes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
